parameters:
    translator.class: Undf\AngularTransBundle\Services\Translator

services:
    undf.twig.utranslations_extension:
            class: Undf\AngularTransBundle\Twig\Extension\UTranslationsExtension
            arguments: [ '@translator']
            tags:
                - { name: twig.extension }
